# Generated by Django 2.2.1 on 2019-07-31 13:00

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StringField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='user domain')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('degree', models.CharField(max_length=50, verbose_name='user degree')),
                ('interests', djongo.models.fields.ArrayModelField(model_container=account.models.Interests)),
                ('paper_collections', djongo.models.fields.ArrayModelField(model_container=account.models.StringField)),
                ('news_collections', djongo.models.fields.ArrayModelField(model_container=account.models.StringField)),
                ('github_collections', djongo.models.fields.ArrayModelField(model_container=account.models.StringField)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
