# Generated by Django 2.2.1 on 2019-07-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
