# Generated by Django 2.2.1 on 2019-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(default='no degree', max_length=50, verbose_name='user degree'),
            preserve_default=False,
        ),
    ]
