# Generated by Django 2.2.1 on 2019-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_actionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='iid',
            new_name='fid',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='end_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='start_time',
            field=models.FloatField(),
        ),
    ]
